editor: source

execute:
  cache: false
  freeze: false

project:
  type: website
  output-dir: docs
  render: [index.qmd]

title: "Sample size estimation"
author: "Daniel Vartanian"
  # name: "Daniel Vartanian"
  # orcid: 0000-0001-7782-759X
  # url: https://linktr.ee/danielvartan
  # email: danvartan@gmail.com
  # corresponding: true
  # affiliation:
  #   - name: University of São Paulo
  #   - Country: Brazil
  #   - url: https://www.usp.br
keyword: >
  sample size. power analysis. pregnancy. sleep. chronobiology.
date: today
date-format: "YYYY-MM-DD"

website:
  repo-url: https://github.com/danielvartan/sample-size
  site-url: https://danielvartan.github.io/sample-size/
  issue-url: https://github.com/danielvartan/sample-size/issues/
  repo-branch: main
  repo-actions: [edit, issue]
  search: false
  navbar:
    title: false
    background: dark
    left:
      - icon: github
        href: https://github.com/danielvartan/sample-size
        aria-label: GitHub

format:
  html:
    locale: en
    language: en-us
    code-fold: show
    code-link: true
    tbl-cap-location: top
    callout-appearance: simple
    csl: english-apa-author-date.csl
    theme: [cosmo, scss/web-theme-light.scss]

google-scholar: false
bibliography: references.bib
